import prisma from '../lib/db';

const ACHIEVEMENTS = [
  // ==================== GLOBAL ACHIEVEMENTS ====================
  {
    code: 'streak_7',
    app_id: 'global',
    name: 'Consistent',
    description: 'Maintain a 7-day streak',
    icon: 'flame',
    xp_reward: 300,
    category: 'streak',
    tier: 1,
    criteria: { type: 'streak_days', count: 7 },
  },
  {
    code: 'streak_30',
    app_id: 'global',
    name: 'Dedicated',
    description: 'Maintain a 30-day streak',
    icon: 'fire',
    xp_reward: 1000,
    category: 'streak',
    tier: 2,
    criteria: { type: 'streak_days', count: 30 },
  },
  {
    code: 'streak_100',
    app_id: 'global',
    name: 'Unstoppable',
    description: 'Maintain a 100-day streak',
    icon: 'trophy',
    xp_reward: 3000,
    category: 'streak',
    tier: 3,
    criteria: { type: 'streak_days', count: 100 },
  },
  {
    code: 'level_5',
    app_id: 'global',
    name: 'Rising Star',
    description: 'Reach Level 5',
    icon: 'star',
    xp_reward: 300,
    category: 'milestone',
    tier: 1,
    criteria: { type: 'global_level', count: 5 },
  },
  {
    code: 'level_10',
    app_id: 'global',
    name: 'Veteran',
    description: 'Reach Level 10',
    icon: 'medal',
    xp_reward: 600,
    category: 'milestone',
    tier: 2,
    criteria: { type: 'global_level', count: 10 },
  },
  {
    code: 'level_25',
    app_id: 'global',
    name: 'Elite',
    description: 'Reach Level 25',
    icon: 'crown',
    xp_reward: 1500,
    category: 'milestone',
    tier: 3,
    criteria: { type: 'global_level', count: 25 },
  },

  // ==================== FITNESS ACHIEVEMENTS ====================
  // Workout milestones
  {
    code: 'fitness_first_workout',
    app_id: 'fitness',
    name: 'First Rep',
    description: 'Complete your first workout',
    icon: 'dumbbell',
    xp_reward: 100,
    category: 'workout',
    tier: 1,
    criteria: { type: 'fitness_workouts', count: 1 },
  },
  {
    code: 'fitness_week_warrior',
    app_id: 'fitness',
    name: 'Week Warrior',
    description: 'Complete 7 workouts',
    icon: 'calendar',
    xp_reward: 300,
    category: 'workout',
    tier: 1,
    criteria: { type: 'fitness_workouts', count: 7 },
  },
  {
    code: 'fitness_month_strong',
    app_id: 'fitness',
    name: 'Month Strong',
    description: 'Complete 30 workouts',
    icon: 'muscle',
    xp_reward: 750,
    category: 'workout',
    tier: 2,
    criteria: { type: 'fitness_workouts', count: 30 },
  },
  {
    code: 'fitness_centurion',
    app_id: 'fitness',
    name: 'Iron Centurion',
    description: 'Complete 100 workouts',
    icon: 'shield',
    xp_reward: 1500,
    category: 'workout',
    tier: 3,
    criteria: { type: 'fitness_workouts', count: 100 },
  },
  {
    code: 'fitness_iron_legend',
    app_id: 'fitness',
    name: 'Iron Legend',
    description: 'Complete 500 workouts',
    icon: 'trophy',
    xp_reward: 5000,
    category: 'workout',
    tier: 4,
    criteria: { type: 'fitness_workouts', count: 500 },
  },
  // Volume achievements
  {
    code: 'fitness_volume_10k',
    app_id: 'fitness',
    name: 'Getting Warmed Up',
    description: 'Lift 10,000 lbs total volume',
    icon: 'weight',
    xp_reward: 200,
    category: 'volume',
    tier: 1,
    criteria: { type: 'stat', stat: 'totalVolume', count: 10000 },
  },
  {
    code: 'fitness_volume_100k',
    app_id: 'fitness',
    name: 'Volume King',
    description: 'Lift 100,000 lbs total volume',
    icon: 'crown',
    xp_reward: 500,
    category: 'volume',
    tier: 2,
    criteria: { type: 'stat', stat: 'totalVolume', count: 100000 },
  },
  {
    code: 'fitness_volume_1m',
    app_id: 'fitness',
    name: 'Million Pound Club',
    description: 'Lift 1,000,000 lbs total volume',
    icon: 'trophy',
    xp_reward: 2000,
    category: 'volume',
    tier: 4,
    criteria: { type: 'stat', stat: 'totalVolume', count: 1000000 },
  },
  // PR achievements
  {
    code: 'fitness_first_pr',
    app_id: 'fitness',
    name: 'Personal Best',
    description: 'Set your first personal record',
    icon: 'medal',
    xp_reward: 150,
    category: 'pr',
    tier: 1,
    criteria: { type: 'stat', stat: 'totalPRs', count: 1 },
  },
  {
    code: 'fitness_pr_hunter',
    app_id: 'fitness',
    name: 'PR Hunter',
    description: 'Set 10 personal records',
    icon: 'target',
    xp_reward: 400,
    category: 'pr',
    tier: 2,
    criteria: { type: 'stat', stat: 'totalPRs', count: 10 },
  },
  {
    code: 'fitness_pr_collector',
    app_id: 'fitness',
    name: 'PR Collector',
    description: 'Set 50 personal records',
    icon: 'star',
    xp_reward: 1000,
    category: 'pr',
    tier: 3,
    criteria: { type: 'stat', stat: 'totalPRs', count: 50 },
  },
  // Sets logged
  {
    code: 'fitness_sets_100',
    app_id: 'fitness',
    name: 'Set for Success',
    description: 'Log 100 sets',
    icon: 'repeat',
    xp_reward: 200,
    category: 'sets',
    tier: 1,
    criteria: { type: 'stat', stat: 'totalSets', count: 100 },
  },
  {
    code: 'fitness_sets_1000',
    app_id: 'fitness',
    name: 'Set Master',
    description: 'Log 1,000 sets',
    icon: 'layers',
    xp_reward: 750,
    category: 'sets',
    tier: 2,
    criteria: { type: 'stat', stat: 'totalSets', count: 1000 },
  },
  {
    code: 'fitness_sets_10000',
    app_id: 'fitness',
    name: 'Set Legend',
    description: 'Log 10,000 sets',
    icon: 'infinity',
    xp_reward: 2500,
    category: 'sets',
    tier: 4,
    criteria: { type: 'stat', stat: 'totalSets', count: 10000 },
  },
  // Exercise variety
  {
    code: 'fitness_exercises_10',
    app_id: 'fitness',
    name: 'Variety Pack',
    description: 'Try 10 different exercises',
    icon: 'shuffle',
    xp_reward: 200,
    category: 'variety',
    tier: 1,
    criteria: { type: 'stat', stat: 'uniqueExercises', count: 10 },
  },
  {
    code: 'fitness_exercises_30',
    app_id: 'fitness',
    name: 'Well Rounded',
    description: 'Try 30 different exercises',
    icon: 'activity',
    xp_reward: 500,
    category: 'variety',
    tier: 2,
    criteria: { type: 'stat', stat: 'uniqueExercises', count: 30 },
  },
  {
    code: 'fitness_exercises_50',
    app_id: 'fitness',
    name: 'Exercise Encyclopedia',
    description: 'Try 50 different exercises',
    icon: 'book',
    xp_reward: 1000,
    category: 'variety',
    tier: 3,
    criteria: { type: 'stat', stat: 'uniqueExercises', count: 50 },
  },

  // ==================== TODAY ACHIEVEMENTS ====================
  // Task milestones
  {
    code: 'today_first_task',
    app_id: 'today',
    name: 'Getting Started',
    description: 'Complete your first task',
    icon: 'check',
    xp_reward: 50,
    category: 'tasks',
    tier: 1,
    criteria: { type: 'today_tasks', count: 1 },
  },
  {
    code: 'today_10_tasks',
    app_id: 'today',
    name: 'Productive',
    description: 'Complete 10 tasks',
    icon: 'clipboard',
    xp_reward: 150,
    category: 'tasks',
    tier: 1,
    criteria: { type: 'today_tasks', count: 10 },
  },
  {
    code: 'today_50_tasks',
    app_id: 'today',
    name: 'Task Master',
    description: 'Complete 50 tasks',
    icon: 'list',
    xp_reward: 400,
    category: 'tasks',
    tier: 2,
    criteria: { type: 'today_tasks', count: 50 },
  },
  {
    code: 'today_100_tasks',
    app_id: 'today',
    name: 'Century Club',
    description: 'Complete 100 tasks',
    icon: 'badge',
    xp_reward: 750,
    category: 'tasks',
    tier: 2,
    criteria: { type: 'today_tasks', count: 100 },
  },
  {
    code: 'today_500_tasks',
    app_id: 'today',
    name: 'Productivity Legend',
    description: 'Complete 500 tasks',
    icon: 'star',
    xp_reward: 2000,
    category: 'tasks',
    tier: 3,
    criteria: { type: 'today_tasks', count: 500 },
  },
  {
    code: 'today_1000_tasks',
    app_id: 'today',
    name: 'Productivity Machine',
    description: 'Complete 1,000 tasks',
    icon: 'trophy',
    xp_reward: 5000,
    category: 'tasks',
    tier: 4,
    criteria: { type: 'today_tasks', count: 1000 },
  },
  // Project achievements
  {
    code: 'today_first_project',
    app_id: 'today',
    name: 'Project Starter',
    description: 'Create your first project',
    icon: 'folder',
    xp_reward: 100,
    category: 'projects',
    tier: 1,
    criteria: { type: 'stat', stat: 'projectsCreated', count: 1 },
  },
  {
    code: 'today_5_projects',
    app_id: 'today',
    name: 'Multi-tasker',
    description: 'Create 5 projects',
    icon: 'folders',
    xp_reward: 300,
    category: 'projects',
    tier: 1,
    criteria: { type: 'stat', stat: 'projectsCreated', count: 5 },
  },
  {
    code: 'today_project_complete',
    app_id: 'today',
    name: 'Mission Complete',
    description: 'Complete all tasks in a project',
    icon: 'flag',
    xp_reward: 200,
    category: 'projects',
    tier: 1,
    criteria: { type: 'stat', stat: 'projectsCompleted', count: 1 },
  },
  {
    code: 'today_10_projects_complete',
    app_id: 'today',
    name: 'Project Closer',
    description: 'Complete 10 projects',
    icon: 'award',
    xp_reward: 750,
    category: 'projects',
    tier: 2,
    criteria: { type: 'stat', stat: 'projectsCompleted', count: 10 },
  },
  // Perfect day achievements
  {
    code: 'today_perfect_day',
    app_id: 'today',
    name: 'Perfect Day',
    description: 'Complete all tasks for a day',
    icon: 'sun',
    xp_reward: 100,
    category: 'daily',
    tier: 1,
    criteria: { type: 'stat', stat: 'perfectDays', count: 1 },
  },
  {
    code: 'today_perfect_week',
    app_id: 'today',
    name: 'Perfect Week',
    description: 'Have 7 perfect days',
    icon: 'calendar',
    xp_reward: 500,
    category: 'daily',
    tier: 2,
    criteria: { type: 'stat', stat: 'perfectDays', count: 7 },
  },
  {
    code: 'today_perfect_month',
    app_id: 'today',
    name: 'Perfect Month',
    description: 'Have 30 perfect days',
    icon: 'crown',
    xp_reward: 1500,
    category: 'daily',
    tier: 3,
    criteria: { type: 'stat', stat: 'perfectDays', count: 30 },
  },
  // Recurring tasks
  {
    code: 'today_first_recurring',
    app_id: 'today',
    name: 'Habit Starter',
    description: 'Create your first recurring task',
    icon: 'repeat',
    xp_reward: 100,
    category: 'habits',
    tier: 1,
    criteria: { type: 'stat', stat: 'recurringTasks', count: 1 },
  },
  {
    code: 'today_habit_builder',
    app_id: 'today',
    name: 'Habit Builder',
    description: 'Complete a recurring task 10 times',
    icon: 'refresh-cw',
    xp_reward: 300,
    category: 'habits',
    tier: 2,
    criteria: { type: 'stat', stat: 'recurringCompletions', count: 10 },
  },
  {
    code: 'today_habit_master',
    app_id: 'today',
    name: 'Habit Master',
    description: 'Complete recurring tasks 100 times',
    icon: 'zap',
    xp_reward: 1000,
    category: 'habits',
    tier: 3,
    criteria: { type: 'stat', stat: 'recurringCompletions', count: 100 },
  },

  // ==================== TRAVEL ACHIEVEMENTS ====================
  // Location milestones
  {
    code: 'travel_first_steps',
    app_id: 'travel',
    name: 'First Steps',
    description: 'Log your first location',
    icon: 'footprints',
    xp_reward: 100,
    category: 'exploration',
    tier: 1,
    criteria: { type: 'locations_count', count: 1 },
  },
  {
    code: 'travel_explorer',
    app_id: 'travel',
    name: 'Explorer',
    description: 'Visit 10 locations',
    icon: 'compass',
    xp_reward: 250,
    category: 'exploration',
    tier: 1,
    criteria: { type: 'locations_count', count: 10 },
  },
  {
    code: 'travel_adventurer',
    app_id: 'travel',
    name: 'Adventurer',
    description: 'Visit 50 locations',
    icon: 'map',
    xp_reward: 500,
    category: 'exploration',
    tier: 2,
    criteria: { type: 'locations_count', count: 50 },
  },
  {
    code: 'travel_globetrotter',
    app_id: 'travel',
    name: 'Globetrotter',
    description: 'Visit 100 locations',
    icon: 'globe',
    xp_reward: 1000,
    category: 'exploration',
    tier: 3,
    criteria: { type: 'locations_count', count: 100 },
  },
  {
    code: 'travel_world_explorer',
    app_id: 'travel',
    name: 'World Explorer',
    description: 'Visit 500 locations',
    icon: 'trophy',
    xp_reward: 5000,
    category: 'exploration',
    tier: 4,
    criteria: { type: 'locations_count', count: 500 },
  },
  // City milestones
  {
    code: 'travel_city_hopper',
    app_id: 'travel',
    name: 'City Hopper',
    description: 'Visit 3 cities',
    icon: 'building',
    xp_reward: 300,
    category: 'cities',
    tier: 1,
    criteria: { type: 'cities_count', count: 3 },
  },
  {
    code: 'travel_city_slicker',
    app_id: 'travel',
    name: 'City Slicker',
    description: 'Visit 5 cities',
    icon: 'buildings',
    xp_reward: 400,
    category: 'cities',
    tier: 1,
    criteria: { type: 'cities_count', count: 5 },
  },
  {
    code: 'travel_cosmopolitan',
    app_id: 'travel',
    name: 'Cosmopolitan',
    description: 'Visit 10 cities',
    icon: 'skyline',
    xp_reward: 750,
    category: 'cities',
    tier: 2,
    criteria: { type: 'cities_count', count: 10 },
  },
  {
    code: 'travel_urban_legend',
    app_id: 'travel',
    name: 'Urban Legend',
    description: 'Visit 25 cities',
    icon: 'crown',
    xp_reward: 1500,
    category: 'cities',
    tier: 3,
    criteria: { type: 'cities_count', count: 25 },
  },
  // Country milestones
  {
    code: 'travel_border_crosser',
    app_id: 'travel',
    name: 'Border Crosser',
    description: 'Visit 2 countries',
    icon: 'flag',
    xp_reward: 300,
    category: 'countries',
    tier: 1,
    criteria: { type: 'countries_count', count: 2 },
  },
  {
    code: 'travel_international',
    app_id: 'travel',
    name: 'International',
    description: 'Visit 5 countries',
    icon: 'plane',
    xp_reward: 750,
    category: 'countries',
    tier: 2,
    criteria: { type: 'countries_count', count: 5 },
  },
  {
    code: 'travel_world_traveler',
    app_id: 'travel',
    name: 'World Traveler',
    description: 'Visit 10 countries',
    icon: 'globe',
    xp_reward: 1500,
    category: 'countries',
    tier: 3,
    criteria: { type: 'countries_count', count: 10 },
  },
  {
    code: 'travel_global_citizen',
    app_id: 'travel',
    name: 'Global Citizen',
    description: 'Visit 25 countries',
    icon: 'trophy',
    xp_reward: 5000,
    category: 'countries',
    tier: 4,
    criteria: { type: 'countries_count', count: 25 },
  },
  // Foodie achievements
  {
    code: 'travel_first_bite',
    app_id: 'travel',
    name: 'First Bite',
    description: 'Log your first restaurant',
    icon: 'utensils',
    xp_reward: 100,
    category: 'foodie',
    tier: 1,
    criteria: { type: 'location_type_count', locationType: 'RESTAURANT', count: 1 },
  },
  {
    code: 'travel_food_critic',
    app_id: 'travel',
    name: 'Food Critic',
    description: 'Visit 10 restaurants',
    icon: 'chef-hat',
    xp_reward: 300,
    category: 'foodie',
    tier: 1,
    criteria: { type: 'location_type_count', locationType: 'RESTAURANT', count: 10 },
  },
  {
    code: 'travel_connoisseur',
    app_id: 'travel',
    name: 'Connoisseur',
    description: 'Visit 50 restaurants',
    icon: 'star',
    xp_reward: 750,
    category: 'foodie',
    tier: 2,
    criteria: { type: 'location_type_count', locationType: 'RESTAURANT', count: 50 },
  },
  {
    code: 'travel_gastronome',
    app_id: 'travel',
    name: 'Gastronome',
    description: 'Visit 100 restaurants',
    icon: 'crown',
    xp_reward: 1500,
    category: 'foodie',
    tier: 3,
    criteria: { type: 'location_type_count', locationType: 'RESTAURANT', count: 100 },
  },
  // Nightlife achievements
  {
    code: 'travel_bar_hopper',
    app_id: 'travel',
    name: 'Bar Hopper',
    description: 'Visit 5 bars',
    icon: 'beer',
    xp_reward: 200,
    category: 'nightlife',
    tier: 1,
    criteria: { type: 'location_type_count', locationType: 'BAR', count: 5 },
  },
  {
    code: 'travel_mixologist',
    app_id: 'travel',
    name: 'Mixologist',
    description: 'Visit 25 bars',
    icon: 'cocktail',
    xp_reward: 500,
    category: 'nightlife',
    tier: 2,
    criteria: { type: 'location_type_count', locationType: 'BAR', count: 25 },
  },
  {
    code: 'travel_nightlife_legend',
    app_id: 'travel',
    name: 'Nightlife Legend',
    description: 'Visit 50 bars',
    icon: 'moon',
    xp_reward: 1000,
    category: 'nightlife',
    tier: 3,
    criteria: { type: 'location_type_count', locationType: 'BAR', count: 50 },
  },
  // Nature achievements
  {
    code: 'travel_nature_lover',
    app_id: 'travel',
    name: 'Nature Lover',
    description: 'Visit 5 nature spots',
    icon: 'tree',
    xp_reward: 200,
    category: 'nature',
    tier: 1,
    criteria: { type: 'location_type_count', locationType: 'NATURE', count: 5 },
  },
  {
    code: 'travel_wilderness_explorer',
    app_id: 'travel',
    name: 'Wilderness Explorer',
    description: 'Visit 25 nature spots',
    icon: 'mountain',
    xp_reward: 500,
    category: 'nature',
    tier: 2,
    criteria: { type: 'location_type_count', locationType: 'NATURE', count: 25 },
  },
  {
    code: 'travel_nature_master',
    app_id: 'travel',
    name: 'Nature Master',
    description: 'Visit 50 nature spots',
    icon: 'sunrise',
    xp_reward: 1000,
    category: 'nature',
    tier: 3,
    criteria: { type: 'location_type_count', locationType: 'NATURE', count: 50 },
  },
  // Culture achievements
  {
    code: 'travel_culture_vulture',
    app_id: 'travel',
    name: 'Culture Vulture',
    description: 'Visit 5 museums or galleries',
    icon: 'palette',
    xp_reward: 200,
    category: 'culture',
    tier: 1,
    criteria: { type: 'location_type_count', locationType: 'MUSEUM', count: 5 },
  },
  {
    code: 'travel_art_lover',
    app_id: 'travel',
    name: 'Art Lover',
    description: 'Visit 15 museums or galleries',
    icon: 'image',
    xp_reward: 500,
    category: 'culture',
    tier: 2,
    criteria: { type: 'location_type_count', locationType: 'MUSEUM', count: 15 },
  },
  // Tourist achievements
  {
    code: 'travel_tourist',
    app_id: 'travel',
    name: 'Tourist',
    description: 'Visit 5 attractions',
    icon: 'camera',
    xp_reward: 200,
    category: 'attractions',
    tier: 1,
    criteria: { type: 'location_type_count', locationType: 'ATTRACTION', count: 5 },
  },
  {
    code: 'travel_sightseer',
    app_id: 'travel',
    name: 'Sightseer',
    description: 'Visit 25 attractions',
    icon: 'landmark',
    xp_reward: 500,
    category: 'attractions',
    tier: 2,
    criteria: { type: 'location_type_count', locationType: 'ATTRACTION', count: 25 },
  },
  // Social achievements
  {
    code: 'travel_first_friend',
    app_id: 'travel',
    name: 'First Friend',
    description: 'Add your first friend',
    icon: 'user-plus',
    xp_reward: 100,
    category: 'social',
    tier: 1,
    criteria: { type: 'friends_count', count: 1 },
  },
  {
    code: 'travel_social_butterfly',
    app_id: 'travel',
    name: 'Social Butterfly',
    description: 'Add 5 friends',
    icon: 'users',
    xp_reward: 300,
    category: 'social',
    tier: 1,
    criteria: { type: 'friends_count', count: 5 },
  },
  {
    code: 'travel_networker',
    app_id: 'travel',
    name: 'Networker',
    description: 'Add 10 friends',
    icon: 'network',
    xp_reward: 500,
    category: 'social',
    tier: 2,
    criteria: { type: 'friends_count', count: 10 },
  },
  // Quest achievements
  {
    code: 'travel_first_quest',
    app_id: 'travel',
    name: 'Quest Starter',
    description: 'Create your first quest',
    icon: 'scroll',
    xp_reward: 100,
    category: 'quests',
    tier: 1,
    criteria: { type: 'stat', stat: 'questsCreated', count: 1 },
  },
  {
    code: 'travel_quest_complete',
    app_id: 'travel',
    name: 'Quest Complete',
    description: 'Complete your first quest',
    icon: 'flag',
    xp_reward: 300,
    category: 'quests',
    tier: 1,
    criteria: { type: 'stat', stat: 'questsCompleted', count: 1 },
  },
  {
    code: 'travel_quest_master',
    app_id: 'travel',
    name: 'Quest Master',
    description: 'Complete 10 quests',
    icon: 'award',
    xp_reward: 1000,
    category: 'quests',
    tier: 2,
    criteria: { type: 'stat', stat: 'questsCompleted', count: 10 },
  },
  // Review achievements
  {
    code: 'travel_first_review',
    app_id: 'travel',
    name: 'Critic',
    description: 'Write your first review',
    icon: 'pen',
    xp_reward: 100,
    category: 'reviews',
    tier: 1,
    criteria: { type: 'stat', stat: 'reviewsWritten', count: 1 },
  },
  {
    code: 'travel_reviewer',
    app_id: 'travel',
    name: 'Reviewer',
    description: 'Write 10 reviews',
    icon: 'edit',
    xp_reward: 300,
    category: 'reviews',
    tier: 1,
    criteria: { type: 'stat', stat: 'reviewsWritten', count: 10 },
  },
  {
    code: 'travel_top_reviewer',
    app_id: 'travel',
    name: 'Top Reviewer',
    description: 'Write 50 reviews',
    icon: 'star',
    xp_reward: 750,
    category: 'reviews',
    tier: 2,
    criteria: { type: 'stat', stat: 'reviewsWritten', count: 50 },
  },
  // Hotlist achievements
  {
    code: 'travel_wishlist_starter',
    app_id: 'travel',
    name: 'Wishlist Starter',
    description: 'Add 5 places to your hotlist',
    icon: 'heart',
    xp_reward: 100,
    category: 'hotlist',
    tier: 1,
    criteria: { type: 'stat', stat: 'hotlistCount', count: 5 },
  },
  {
    code: 'travel_bucket_list',
    app_id: 'travel',
    name: 'Bucket List',
    description: 'Add 25 places to your hotlist',
    icon: 'bookmark',
    xp_reward: 300,
    category: 'hotlist',
    tier: 2,
    criteria: { type: 'stat', stat: 'hotlistCount', count: 25 },
  },
];

async function seedAchievements() {
  console.log('Seeding achievements...');

  for (const achievement of ACHIEVEMENTS) {
    await prisma.achievements.upsert({
      where: { code: achievement.code },
      update: {
        name: achievement.name,
        description: achievement.description,
        icon: achievement.icon,
        xp_reward: achievement.xp_reward,
        category: achievement.category,
        tier: achievement.tier,
        criteria: achievement.criteria,
      },
      create: achievement,
    });
    console.log(`  ✓ ${achievement.code}`);
  }

  console.log(`\nSeeded ${ACHIEVEMENTS.length} achievements`);
}

seedAchievements()
  .then(() => {
    console.log('Done!');
    process.exit(0);
  })
  .catch((error) => {
    console.error('Error seeding achievements:', error);
    process.exit(1);
  });
