import prisma from '../lib/db';

const ACHIEVEMENTS = [
  // ==================== GLOBAL ACHIEVEMENTS ====================
  {
    code: 'streak_7',
    app_id: 'global',
    name: 'Consistent',
    description: 'Maintain a 7-day streak',
    icon: 'flame',
    xp_reward: 300,
    category: 'streak',
    tier: 1,
    criteria: { type: 'streak_days', count: 7 },
  },
  {
    code: 'streak_30',
    app_id: 'global',
    name: 'Dedicated',
    description: 'Maintain a 30-day streak',
    icon: 'fire',
    xp_reward: 1000,
    category: 'streak',
    tier: 2,
    criteria: { type: 'streak_days', count: 30 },
  },
  {
    code: 'streak_100',
    app_id: 'global',
    name: 'Unstoppable',
    description: 'Maintain a 100-day streak',
    icon: 'trophy',
    xp_reward: 3000,
    category: 'streak',
    tier: 3,
    criteria: { type: 'streak_days', count: 100 },
  },
  {
    code: 'level_5',
    app_id: 'global',
    name: 'Rising Star',
    description: 'Reach Level 5',
    icon: 'star',
    xp_reward: 300,
    category: 'milestone',
    tier: 1,
    criteria: { type: 'global_level', count: 5 },
  },
  {
    code: 'level_10',
    app_id: 'global',
    name: 'Veteran',
    description: 'Reach Level 10',
    icon: 'medal',
    xp_reward: 600,
    category: 'milestone',
    tier: 2,
    criteria: { type: 'global_level', count: 10 },
  },
  {
    code: 'level_25',
    app_id: 'global',
    name: 'Elite',
    description: 'Reach Level 25',
    icon: 'crown',
    xp_reward: 1500,
    category: 'milestone',
    tier: 3,
    criteria: { type: 'global_level', count: 25 },
  },

  // ==================== FITNESS ACHIEVEMENTS ====================
  {
    code: 'fitness_first_workout',
    app_id: 'fitness',
    name: 'First Rep',
    description: 'Complete your first workout',
    icon: 'dumbbell',
    xp_reward: 100,
    category: 'fitness',
    tier: 1,
    criteria: { type: 'fitness_workouts', count: 1 },
  },
  {
    code: 'fitness_week_warrior',
    app_id: 'fitness',
    name: 'Week Warrior',
    description: 'Complete 7 workouts',
    icon: 'calendar',
    xp_reward: 300,
    category: 'fitness',
    tier: 1,
    criteria: { type: 'fitness_workouts', count: 7 },
  },
  {
    code: 'fitness_month_strong',
    app_id: 'fitness',
    name: 'Month Strong',
    description: 'Complete 30 workouts',
    icon: 'muscle',
    xp_reward: 750,
    category: 'fitness',
    tier: 2,
    criteria: { type: 'fitness_workouts', count: 30 },
  },
  {
    code: 'fitness_centurion',
    app_id: 'fitness',
    name: 'Iron Centurion',
    description: 'Complete 100 workouts',
    icon: 'shield',
    xp_reward: 1500,
    category: 'fitness',
    tier: 3,
    criteria: { type: 'fitness_workouts', count: 100 },
  },
  {
    code: 'fitness_volume_10k',
    app_id: 'fitness',
    name: 'Getting Warmed Up',
    description: 'Lift 10,000 lbs total volume',
    icon: 'weight',
    xp_reward: 200,
    category: 'fitness',
    tier: 1,
    criteria: { type: 'stat', stat: 'totalVolume', count: 10000 },
  },
  {
    code: 'fitness_volume_100k',
    app_id: 'fitness',
    name: 'Volume King',
    description: 'Lift 100,000 lbs total volume',
    icon: 'crown',
    xp_reward: 500,
    category: 'fitness',
    tier: 2,
    criteria: { type: 'stat', stat: 'totalVolume', count: 100000 },
  },
  {
    code: 'fitness_volume_1m',
    app_id: 'fitness',
    name: 'Million Pound Club',
    description: 'Lift 1,000,000 lbs total volume',
    icon: 'trophy',
    xp_reward: 2000,
    category: 'fitness',
    tier: 4,
    criteria: { type: 'stat', stat: 'totalVolume', count: 1000000 },
  },

  // ==================== TODAY ACHIEVEMENTS ====================
  {
    code: 'today_first_task',
    app_id: 'today',
    name: 'Getting Started',
    description: 'Complete your first task',
    icon: 'check',
    xp_reward: 50,
    category: 'productivity',
    tier: 1,
    criteria: { type: 'today_tasks', count: 1 },
  },
  {
    code: 'today_10_tasks',
    app_id: 'today',
    name: 'Productive',
    description: 'Complete 10 tasks',
    icon: 'clipboard',
    xp_reward: 150,
    category: 'productivity',
    tier: 1,
    criteria: { type: 'today_tasks', count: 10 },
  },
  {
    code: 'today_50_tasks',
    app_id: 'today',
    name: 'Task Master',
    description: 'Complete 50 tasks',
    icon: 'list',
    xp_reward: 400,
    category: 'productivity',
    tier: 2,
    criteria: { type: 'today_tasks', count: 50 },
  },
  {
    code: 'today_100_tasks',
    app_id: 'today',
    name: 'Century Club',
    description: 'Complete 100 tasks',
    icon: 'badge',
    xp_reward: 750,
    category: 'productivity',
    tier: 2,
    criteria: { type: 'today_tasks', count: 100 },
  },
  {
    code: 'today_500_tasks',
    app_id: 'today',
    name: 'Productivity Legend',
    description: 'Complete 500 tasks',
    icon: 'star',
    xp_reward: 2000,
    category: 'productivity',
    tier: 3,
    criteria: { type: 'today_tasks', count: 500 },
  },

  // ==================== TRAVEL ACHIEVEMENTS (existing) ====================
  {
    code: 'travel_first_steps',
    app_id: 'travel',
    name: 'First Steps',
    description: 'Log your first location',
    icon: 'footprints',
    xp_reward: 100,
    category: 'exploration',
    tier: 1,
    criteria: { type: 'stat', stat: 'locations', count: 1 },
  },
  {
    code: 'travel_explorer',
    app_id: 'travel',
    name: 'Explorer',
    description: 'Visit 10 locations',
    icon: 'compass',
    xp_reward: 250,
    category: 'exploration',
    tier: 1,
    criteria: { type: 'stat', stat: 'locations', count: 10 },
  },
  {
    code: 'travel_adventurer',
    app_id: 'travel',
    name: 'Adventurer',
    description: 'Visit 50 locations',
    icon: 'map',
    xp_reward: 500,
    category: 'exploration',
    tier: 2,
    criteria: { type: 'stat', stat: 'locations', count: 50 },
  },
  {
    code: 'travel_globetrotter',
    app_id: 'travel',
    name: 'Globetrotter',
    description: 'Visit 100 locations',
    icon: 'globe',
    xp_reward: 1000,
    category: 'exploration',
    tier: 3,
    criteria: { type: 'stat', stat: 'locations', count: 100 },
  },
  {
    code: 'travel_city_hopper',
    app_id: 'travel',
    name: 'City Hopper',
    description: 'Visit 3 cities',
    icon: 'building',
    xp_reward: 300,
    category: 'exploration',
    tier: 1,
    criteria: { type: 'stat', stat: 'cities', count: 3 },
  },
  {
    code: 'travel_cosmopolitan',
    app_id: 'travel',
    name: 'Cosmopolitan',
    description: 'Visit 10 cities',
    icon: 'buildings',
    xp_reward: 750,
    category: 'exploration',
    tier: 2,
    criteria: { type: 'stat', stat: 'cities', count: 10 },
  },
];

async function seedAchievements() {
  console.log('Seeding achievements...');

  for (const achievement of ACHIEVEMENTS) {
    await prisma.achievements.upsert({
      where: { code: achievement.code },
      update: {
        name: achievement.name,
        description: achievement.description,
        icon: achievement.icon,
        xp_reward: achievement.xp_reward,
        category: achievement.category,
        tier: achievement.tier,
        criteria: achievement.criteria,
      },
      create: achievement,
    });
    console.log(`  ✓ ${achievement.code}`);
  }

  console.log(`\nSeeded ${ACHIEVEMENTS.length} achievements`);
}

seedAchievements()
  .then(() => {
    console.log('Done!');
    process.exit(0);
  })
  .catch((error) => {
    console.error('Error seeding achievements:', error);
    process.exit(1);
  });
